[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://formspree.io https://*.googletagmanager.com https://*.google-analytics.com https://*.analytics.google.com https://google.com https://www.google.com https://*.g.doubleclick.net; frame-ancestors 'none';"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=3600"
